{% set name = "rptools" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rptools/archive/{{ version }}.tar.gz
  sha256: 4cdf498fed9f0a5cde4cf776b1964e47dda3682fad9349a77e4218301b44ca6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - brs_utils
    - cobra
    - rdkit
    - python-libsbml
    - numpy <=1.22.4
    - pandas
    - scipy
    - equilibrator-api
    - openbabel
    - colored
    - networkx >=2.5
    - filetype
    - rr_cache
    - rxn_rebuild
    - chemlite
    - h5py
    - xgboost
    - beautifulsoup4
    - sqlalchemy =1.4.31

test:
  source_files:
    - tests
  imports:
    - rptools
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
  commands:
    - python -m rptools --help
    - cd tests
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/rptools
  summary: Suite of tools that work on rpSBML data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
    - kenza12
